//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: protos/Login.proto
namespace Action.Model.Protobuf
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BackgroundLoginArgs")]
  public partial class BackgroundLoginArgs : global::ProtoBuf.IExtensible
  {
    public BackgroundLoginArgs() {}
    

    private string _Account = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Account", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Account
    {
      get { return _Account; }
      set { _Account = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}