//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: protos/_SceneArgs.proto
// Note: requires additional types generated from: protobuf-net.proto
// Note: requires additional types generated from: protos/PlayerInfo.proto
namespace Action.Model
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SnapPlayersArgs")]
  public partial class SnapPlayersArgs : global::ProtoBuf.IExtensible
  {
    public SnapPlayersArgs() {}
    

    private Action.Model.Role _Role = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Role", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Action.Model.Role Role
    {
      get { return _Role; }
      set { _Role = value; }
    }

    private int _X = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"X", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int X
    {
      get { return _X; }
      set { _X = value; }
    }

    private int _Y = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Y
    {
      get { return _Y; }
      set { _Y = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}